In [2]:
import numpy as np 
import glob
import os 
import umap
import numpy as np


In [93]:
total_sample_size = 100
slice_size = 10
sample_size_per_slice = total_sample_size / slices_size
latent_vector_size = 128
umap_neighbours = 50
umap_min_distatnce = 0.1
umap_dimensions = 2
output_path = "./output/"
csv_filename = "random_nums_3d_embeddings"
csv_header = "x, y, z"
csv_comments = "" # should the csv header have any text before the labels? (like '#' for python comment)
csv_fmt = "%f" #fmt "%f" ensures floats are not saved in the sci annotation format to to the csv file

In [7]:
# def main():
# 	# create output folder
# 	if not os.path.isdir(output_path):
# 	    os.mkdir(output_path)

total_sample = np.random.normal(0, 1, (total_sample_size, latent_vector_size))



In [8]:
	print("Running umap")	
	# get embeddings
	reducer = umap.UMAP(n_neighbors=umap_neighbours, min_dist=umap_min_distatnce, n_components=umap_dimensions)
	embeddings = reducer.fit_transform(total_sample)
    
	# create 3rd column for z index, where z is always 0
# 	embeddings = np.insert(embeddings, 2, 0, 1)


# 	# save the embeddings
# 	csv_path = os.path.join(output_path, csv_filename + ".csv")
# 	np.savetxt(csv_path, 
# 				embeddings, 
# 				delimiter=",", 
# 				header=csv_header, 
# 				comments=csv_comments,				
# 				fmt=csv_fmt) 
# 	print("Umap embeddings saved at: " + csv_path)	


Running umap


OMP: Info #273: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.


In [81]:
s = np.random.choice(embeddings, size=(10,2), replace=False)
#embeddings.shape

ValueError: a must be 1-dimensional

In [15]:
arr = np.array([1,2,3,4])
s =  np.random.choice(arr, size=2, replace=False) # replace=False - each value can be selected only once
print(arr)
print(s)
# get random indexes
# use them to get items from total sample to slice arr
# use them to delete items from total sample
# consider boolean mask to do the removal?

[1 2 3 4]
[1 1]


In [80]:
indexes = np.arange(0, 12)
slice_size = 3
for _ in range(4):
    selection = np.random.choice(indexes, size=slice_size, replace=False)
    res = np.flatnonzero(np.isin(indexes, selection))
    indexes = np.delete(indexes, res)
    print("all indexes: ")
    print(indexes)
    print("selection: ")
    print(selection)
    print("deletion indexes: ")
    print(res)

#np.where(indexes == selection)
#selection_indixes = np.array([np.where(indexes == s) for s in selection])

#print(selection)
#print(selection_indixes)
#indexes1 = np.delete(indexes, selection)
#np.where(indexes == [0,1])

all indexes: 
[ 0  1  2  4  5  7  9 10 11]
selection: 
[3 8 6]
deletion indexes: 
[3 6 8]
all indexes: 
[ 0  1  4  9 10 11]
selection: 
[7 5 2]
deletion indexes: 
[2 4 5]
all indexes: 
[ 0  9 10]
selection: 
[ 1 11  4]
deletion indexes: 
[1 2 5]
all indexes: 
[]
selection: 
[10  9  0]
deletion indexes: 
[0 1 2]


In [144]:
assert(total_sample_size % slice_size == 0)

embs = np.copy(embeddings)
embs_indexes = np.arange(embs.shape[0])

sliced_embs = np.empty((slice_size, slice_size, 4))

print(sliced_embs.shape)
for slice_index in range(int(total_sample_size/slice_size)):
    embeddings_slice_indexes = np.random.choice(embs_indexes,size=slice_size, replace=False)
    slice_indexes = np.flatnonzero(np.isin(embs, embeddings_slice_indexes))
    embs_slice = embs[embeddings_slice_indexes]
    embs_slice = np.insert(embs_slice, 2, slice_index, 1)
    embs_ids = np.arange(slice_index*slice_size, slice_index*slice_size+slice_size)
    embs_slice = np.insert(embs_slice, 3, embs_ids, 1)
    sliced_embs[slice_index] = embs_slice
   # print(embs_slice.shape)
    embs_indexes = np.delete(embs_indexes, slice_indexes)

sliced_embs = np.reshape(sliced_embs, (total_sample_size, 4))

(10, 10, 4)
